<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"><!-- Begin Jekyll SEO tag v2.6.1 -->
<title>优雅地 async/await | 牛さんの部落格</title>
<meta name="generator" content="Jekyll v4.1.1" />
<meta property="og:title" content="优雅地 async/await" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="优雅地 async/await async/await 虽然取代了回调，使用类似同步的代码组织方式让代码更加简洁美观，但错误处理时需要加 try/catch。 比如下面这样，一个简单的 Node.js 中使用 async/await 的场景： const fetch = require(&quot;node-fetch&quot;); async function getData() { const url = &quot;https://api.github.com/users/wayou&quot;; try { const response = await fetch(url); const data = await response.json(); console.log(data); } catch (error) { throw error; } } getData(); 像这样的异步场景，Node.js 中会有很多。如果都通过 try/catch 来错误处理，数量多了之后也是不太美观的。 将异步进行一层封装 因为本质上 async/await 是 Promise，我们可以封装一个简单的方法，将错误处理变得更优雅。 比如下面这样： function await2js(promise) { return promise.then(result =&gt; [undefined, result]).catch(error =&gt; [error, undefined]); } 该方法始终返回两个结果，第一个是错误，第二个是数据，这和 Node.js 中回调的入参 (err,data)=&gt;void 是一致的，使得这层包装很 Node.js，一点也不会感到奇怪。 所以改造后的使用示例： async function getData() { const url = &quot;https://api.github.com/users/wayou&quot;; const [error, response] = await await2js(fetch(url)); if (error) { throw error; } const [error2, data] = await await2js(response.json()); if (error2) { throw error2; } console.log(data); } 这层封装针对单个 await，不像 try/catch 那么粗犷一下子包含再次 await。也不是说 try/catch 不能精细地处理错误，但脑补一下把上面两次 await 都用 try/catch 的模样。 当然，如果嫌麻烦，也可通过 Promise.all() 或 Promise 的链式调用将多次 await 操作合并，只处理一次错误。 TypeScript 版本 function await2js&lt;T, K = Error&gt;(promise: Promise&lt;T&gt;) { return promise .then&lt;[undefined, T]&gt;((response: T) =&gt; [undefined, response]) .catch&lt;[K, undefined]&gt;((error: K) =&gt; [error, undefined]); } 这里有个相应的 npm 包便是做这事情的 await-to-js。 相关资源 来自 @markdalgleish 关于本主题的推文 npm - await-to-js" />
<meta property="og:description" content="优雅地 async/await async/await 虽然取代了回调，使用类似同步的代码组织方式让代码更加简洁美观，但错误处理时需要加 try/catch。 比如下面这样，一个简单的 Node.js 中使用 async/await 的场景： const fetch = require(&quot;node-fetch&quot;); async function getData() { const url = &quot;https://api.github.com/users/wayou&quot;; try { const response = await fetch(url); const data = await response.json(); console.log(data); } catch (error) { throw error; } } getData(); 像这样的异步场景，Node.js 中会有很多。如果都通过 try/catch 来错误处理，数量多了之后也是不太美观的。 将异步进行一层封装 因为本质上 async/await 是 Promise，我们可以封装一个简单的方法，将错误处理变得更优雅。 比如下面这样： function await2js(promise) { return promise.then(result =&gt; [undefined, result]).catch(error =&gt; [error, undefined]); } 该方法始终返回两个结果，第一个是错误，第二个是数据，这和 Node.js 中回调的入参 (err,data)=&gt;void 是一致的，使得这层包装很 Node.js，一点也不会感到奇怪。 所以改造后的使用示例： async function getData() { const url = &quot;https://api.github.com/users/wayou&quot;; const [error, response] = await await2js(fetch(url)); if (error) { throw error; } const [error2, data] = await await2js(response.json()); if (error2) { throw error2; } console.log(data); } 这层封装针对单个 await，不像 try/catch 那么粗犷一下子包含再次 await。也不是说 try/catch 不能精细地处理错误，但脑补一下把上面两次 await 都用 try/catch 的模样。 当然，如果嫌麻烦，也可通过 Promise.all() 或 Promise 的链式调用将多次 await 操作合并，只处理一次错误。 TypeScript 版本 function await2js&lt;T, K = Error&gt;(promise: Promise&lt;T&gt;) { return promise .then&lt;[undefined, T]&gt;((response: T) =&gt; [undefined, response]) .catch&lt;[K, undefined]&gt;((error: K) =&gt; [error, undefined]); } 这里有个相应的 npm 包便是做这事情的 await-to-js。 相关资源 来自 @markdalgleish 关于本主题的推文 npm - await-to-js" />
<link rel="canonical" href="http://localhost:4000/2019/04/25/%E4%BC%98%E9%9B%85%E5%9C%B0-async-await.html" />
<meta property="og:url" content="http://localhost:4000/2019/04/25/%E4%BC%98%E9%9B%85%E5%9C%B0-async-await.html" />
<meta property="og:site_name" content="牛さんの部落格" />
<meta property="og:type" content="article" />
<meta property="article:published_time" content="2019-04-25T23:04:00+08:00" />
<script type="application/ld+json">
{"url":"http://localhost:4000/2019/04/25/%E4%BC%98%E9%9B%85%E5%9C%B0-async-await.html","mainEntityOfPage":{"@type":"WebPage","@id":"http://localhost:4000/2019/04/25/%E4%BC%98%E9%9B%85%E5%9C%B0-async-await.html"},"description":"优雅地 async/await async/await 虽然取代了回调，使用类似同步的代码组织方式让代码更加简洁美观，但错误处理时需要加 try/catch。 比如下面这样，一个简单的 Node.js 中使用 async/await 的场景： const fetch = require(&quot;node-fetch&quot;); async function getData() { const url = &quot;https://api.github.com/users/wayou&quot;; try { const response = await fetch(url); const data = await response.json(); console.log(data); } catch (error) { throw error; } } getData(); 像这样的异步场景，Node.js 中会有很多。如果都通过 try/catch 来错误处理，数量多了之后也是不太美观的。 将异步进行一层封装 因为本质上 async/await 是 Promise，我们可以封装一个简单的方法，将错误处理变得更优雅。 比如下面这样： function await2js(promise) { return promise.then(result =&gt; [undefined, result]).catch(error =&gt; [error, undefined]); } 该方法始终返回两个结果，第一个是错误，第二个是数据，这和 Node.js 中回调的入参 (err,data)=&gt;void 是一致的，使得这层包装很 Node.js，一点也不会感到奇怪。 所以改造后的使用示例： async function getData() { const url = &quot;https://api.github.com/users/wayou&quot;; const [error, response] = await await2js(fetch(url)); if (error) { throw error; } const [error2, data] = await await2js(response.json()); if (error2) { throw error2; } console.log(data); } 这层封装针对单个 await，不像 try/catch 那么粗犷一下子包含再次 await。也不是说 try/catch 不能精细地处理错误，但脑补一下把上面两次 await 都用 try/catch 的模样。 当然，如果嫌麻烦，也可通过 Promise.all() 或 Promise 的链式调用将多次 await 操作合并，只处理一次错误。 TypeScript 版本 function await2js&lt;T, K = Error&gt;(promise: Promise&lt;T&gt;) { return promise .then&lt;[undefined, T]&gt;((response: T) =&gt; [undefined, response]) .catch&lt;[K, undefined]&gt;((error: K) =&gt; [error, undefined]); } 这里有个相应的 npm 包便是做这事情的 await-to-js。 相关资源 来自 @markdalgleish 关于本主题的推文 npm - await-to-js","@type":"BlogPosting","headline":"优雅地 async/await","dateModified":"2019-04-25T23:04:00+08:00","datePublished":"2019-04-25T23:04:00+08:00","@context":"https://schema.org"}</script>
<!-- End Jekyll SEO tag -->
<link rel="stylesheet" href="/assets/main.css"><link type="application/atom+xml" rel="alternate" href="http://localhost:4000/feed.xml" title="牛さんの部落格" /></head>
<body><header class="site-header" role="banner">

  <div class="wrapper"><a class="site-title" rel="author" href="/">牛さんの部落格</a><nav class="site-nav">
        <input type="checkbox" id="nav-trigger" class="nav-trigger" />
        <label for="nav-trigger">
          <span class="menu-icon">
            <svg viewBox="0 0 18 15" width="18px" height="15px">
              <path d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.032C17.335,0,18,0.665,18,1.484L18,1.484z M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.032C17.335,6.031,18,6.696,18,7.516L18,7.516z M18,13.516C18,14.335,17.335,15,16.516,15H1.484 C0.665,15,0,14.335,0,13.516l0,0c0-0.82,0.665-1.483,1.484-1.483h15.032C17.335,12.031,18,12.695,18,13.516L18,13.516z"/>
            </svg>
          </span>
        </label>

        <div class="trigger"><a class="page-link" href="/about/">About</a></div>
      </nav></div>
</header>
<main class="page-content" aria-label="Content">
      <div class="wrapper">
        <article class="post h-entry" itemscope itemtype="http://schema.org/BlogPosting">

  <header class="post-header">
    <h1 class="post-title p-name" itemprop="name headline">优雅地 async/await</h1>
    <p class="post-meta">
      <time class="dt-published" datetime="2019-04-25T23:04:00+08:00" itemprop="datePublished">Apr 25, 2019
      </time></p>
  </header>

  <div class="post-content e-content" itemprop="articleBody">
    <h1 id="优雅地-asyncawait">优雅地 <code class="language-plaintext highlighter-rouge">async/await</code></h1>

<p><code class="language-plaintext highlighter-rouge">async/await</code> 虽然取代了回调，使用类似同步的代码组织方式让代码更加简洁美观，但错误处理时需要加 <code class="language-plaintext highlighter-rouge">try/catch</code>。</p>

<p>比如下面这样，一个简单的 Node.js 中使用 <code class="language-plaintext highlighter-rouge">async/await</code> 的场景：</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">const</span> <span class="nx">fetch</span> <span class="o">=</span> <span class="nx">require</span><span class="p">(</span><span class="dl">"</span><span class="s2">node-fetch</span><span class="dl">"</span><span class="p">);</span>

<span class="k">async</span> <span class="kd">function</span> <span class="nx">getData</span><span class="p">()</span> <span class="p">{</span>
  <span class="kd">const</span> <span class="nx">url</span> <span class="o">=</span> <span class="dl">"</span><span class="s2">https://api.github.com/users/wayou</span><span class="dl">"</span><span class="p">;</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="kd">const</span> <span class="nx">response</span> <span class="o">=</span> <span class="k">await</span> <span class="nx">fetch</span><span class="p">(</span><span class="nx">url</span><span class="p">);</span>
    <span class="kd">const</span> <span class="nx">data</span> <span class="o">=</span> <span class="k">await</span> <span class="nx">response</span><span class="p">.</span><span class="nx">json</span><span class="p">();</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">data</span><span class="p">);</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">error</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="nx">error</span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>

<span class="nx">getData</span><span class="p">();</span>
</code></pre></div></div>

<p>像这样的异步场景，Node.js 中会有很多。如果都通过 <code class="language-plaintext highlighter-rouge">try/catch</code> 来错误处理，数量多了之后也是不太美观的。</p>

<h2 id="将异步进行一层封装">将异步进行一层封装</h2>

<p>因为本质上 <code class="language-plaintext highlighter-rouge">async/await</code> 是 <a href="https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise">Promise</a>，我们可以封装一个简单的方法，将错误处理变得更优雅。</p>

<p>比如下面这样：</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">await2js</span><span class="p">(</span><span class="nx">promise</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="nx">promise</span><span class="p">.</span><span class="nx">then</span><span class="p">(</span><span class="nx">result</span> <span class="o">=&gt;</span> <span class="p">[</span><span class="kc">undefined</span><span class="p">,</span> <span class="nx">result</span><span class="p">]).</span><span class="k">catch</span><span class="p">(</span><span class="nx">error</span> <span class="o">=&gt;</span> <span class="p">[</span><span class="nx">error</span><span class="p">,</span> <span class="kc">undefined</span><span class="p">]);</span>
<span class="p">}</span>
</code></pre></div></div>

<p>该方法始终返回两个结果，第一个是错误，第二个是数据，这和 Node.js 中回调的入参 <code class="language-plaintext highlighter-rouge">(err,data)=&gt;void</code> 是一致的，使得这层包装很 Node.js，一点也不会感到奇怪。</p>

<p>所以改造后的使用示例：</p>

<div class="language-js highlighter-rouge"><div class="highlight"><pre class="highlight"><code>
<span class="k">async</span> <span class="kd">function</span> <span class="nx">getData</span><span class="p">()</span> <span class="p">{</span>
  <span class="kd">const</span> <span class="nx">url</span> <span class="o">=</span> <span class="dl">"</span><span class="s2">https://api.github.com/users/wayou</span><span class="dl">"</span><span class="p">;</span>
  <span class="kd">const</span> <span class="p">[</span><span class="nx">error</span><span class="p">,</span> <span class="nx">response</span><span class="p">]</span> <span class="o">=</span> <span class="k">await</span> <span class="nx">await2js</span><span class="p">(</span><span class="nx">fetch</span><span class="p">(</span><span class="nx">url</span><span class="p">));</span>
  <span class="k">if</span> <span class="p">(</span><span class="nx">error</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="nx">error</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="kd">const</span> <span class="p">[</span><span class="nx">error2</span><span class="p">,</span> <span class="nx">data</span><span class="p">]</span> <span class="o">=</span> <span class="k">await</span> <span class="nx">await2js</span><span class="p">(</span><span class="nx">response</span><span class="p">.</span><span class="nx">json</span><span class="p">());</span>
  <span class="k">if</span> <span class="p">(</span><span class="nx">error2</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="nx">error2</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">data</span><span class="p">);</span>
<span class="p">}</span>
</code></pre></div></div>

<p>这层封装针对单个 <code class="language-plaintext highlighter-rouge">await</code>，不像 <code class="language-plaintext highlighter-rouge">try/catch</code> 那么粗犷一下子包含再次 <code class="language-plaintext highlighter-rouge">await</code>。也不是说 <code class="language-plaintext highlighter-rouge">try/catch</code> 不能精细地处理错误，但脑补一下把上面两次 <code class="language-plaintext highlighter-rouge">await</code> 都用 <code class="language-plaintext highlighter-rouge">try/catch</code> 的模样。</p>

<p>当然，如果嫌麻烦，也可通过 <code class="language-plaintext highlighter-rouge">Promise.all()</code> 或 Promise 的链式调用将多次 <code class="language-plaintext highlighter-rouge">await</code> 操作合并，只处理一次错误。</p>

<h3 id="typescript-版本">TypeScript 版本</h3>

<div class="language-ts highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">await2js</span><span class="o">&lt;</span><span class="nx">T</span><span class="p">,</span> <span class="nx">K</span> <span class="o">=</span> <span class="nb">Error</span><span class="o">&gt;</span><span class="p">(</span><span class="nx">promise</span><span class="p">:</span> <span class="nb">Promise</span><span class="o">&lt;</span><span class="nx">T</span><span class="o">&gt;</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="nx">promise</span>
    <span class="p">.</span><span class="nx">then</span><span class="o">&lt;</span><span class="p">[</span><span class="kc">undefined</span><span class="p">,</span> <span class="nx">T</span><span class="p">]</span><span class="o">&gt;</span><span class="p">((</span><span class="nx">response</span><span class="p">:</span> <span class="nx">T</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">[</span><span class="kc">undefined</span><span class="p">,</span> <span class="nx">response</span><span class="p">])</span>
    <span class="p">.</span><span class="k">catch</span><span class="o">&lt;</span><span class="p">[</span><span class="nx">K</span><span class="p">,</span> <span class="kc">undefined</span><span class="p">]</span><span class="o">&gt;</span><span class="p">((</span><span class="nx">error</span><span class="p">:</span> <span class="nx">K</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">[</span><span class="nx">error</span><span class="p">,</span> <span class="kc">undefined</span><span class="p">]);</span>
<span class="p">}</span>
</code></pre></div></div>

<p>这里有个相应的 npm 包便是做这事情的 <a href="https://github.com/scopsy/await-to-js">await-to-js</a>。</p>

<h2 id="相关资源">相关资源</h2>

<ul>
  <li><a href="https://twitter.com/markdalgleish/status/1120224474291294208">来自 @markdalgleish 关于本主题的推文</a></li>
  <li><a href="https://www.npmjs.com/package/await-to-js">npm - await-to-js</a></li>
</ul>


  </div><a class="u-url" href="/2019/04/25/%E4%BC%98%E9%9B%85%E5%9C%B0-async-await.html" hidden></a>
</article>

      </div>
    </main><footer class="site-footer h-card">
  <data class="u-url" href="/"></data>

  <div class="wrapper">

    <h2 class="footer-heading">牛さんの部落格</h2>

    <div class="footer-col-wrapper">
      <div class="footer-col footer-col-1">
        <ul class="contact-list">
          <li class="p-name">牛さんの部落格</li><li><a class="u-email" href="mailto:liuwayong@gmail.com">liuwayong@gmail.com</a></li></ul>
      </div>

      <div class="footer-col footer-col-2"><ul class="social-media-list"><li><a href="https://github.com/jekyll"><svg class="svg-icon"><use xlink:href="/assets/minima-social-icons.svg#github"></use></svg> <span class="username">jekyll</span></a></li><li><a href="https://www.twitter.com/jekyllrb"><svg class="svg-icon"><use xlink:href="/assets/minima-social-icons.svg#twitter"></use></svg> <span class="username">jekyllrb</span></a></li></ul>
</div>

      <div class="footer-col footer-col-3">
        <p>notes about the coding life</p>
      </div>
    </div>

  </div>

</footer>
</body>

</html>
